#!/bin/bash

set -e  # Exit on any error

echo "🚀 Building all Slidev presentations..."

# Clean dist directory
rm -rf dist
mkdir -p dist

# Find all markdown files (these are our presentations)
PRESENTATIONS=$(find . -maxdepth 1 -name "*.md" -type f)

# Check if we have any presentations
if [ -z "$PRESENTATIONS" ]; then
    echo "⚠️  No presentation files found (*.md)"
    exit 1
fi

# Copy the index.html to dist root (generated by generate-index.js)
if [ -f "index.html" ]; then
    echo "📋 Copying index.html to dist..."
    cp index.html dist/
else
    echo "⚠️  No index.html found - run generate-index.js first"
    exit 1
fi

# Build each presentation
for file in $PRESENTATIONS; do
    # Get filename without extension
    filename=$(basename "$file" .md)
    
    echo "📊 Building: $filename"
    
    # Build with proper base path
    npx slidev build "$file" \
        --base "/$filename/" \
        --out "dist/$filename"
    
    echo "✅ Built: $filename"
done

echo ""
echo "🎉 All presentations built successfully!"
echo ""
echo "📁 Structure:"
echo "   dist/"
echo "   ├── index.html (static index page)"
for file in $PRESENTATIONS; do
    filename=$(basename "$file" .md)
    echo "   └── $filename/ (presentation)"
done
echo ""
echo "🧪 Test locally: npm run preview"