<?php

return [
    'year' => '2025/26',
    'club_name' => 'Rotaract Club of Patan South',
    'sponsoring_club' => 'Rotary Club of Patan South',
    'club_number' => '90407',
    'rid' => '3292 Nepal and Bhutan',
    'venue' => "St. Xavier's College, Jawalakhel",
    'meeting_day' => 'Saturdays (bimonthly)',
    'member_prefix' => 'Rtr.',
    'president' => 'Rtr. Aakrity Rijal',
    'presiding_officer' => 'Rtr. Aakrity Rijal',
    'gm_start_number' => 269,
    'bod' => [
        ['name' => 'Aakrity Rijal', 'position' => 'President'],
        ['name' => 'Surakshya Niraula', 'position' => 'Immediate Past President'],
        ['name' => 'Suprim Dahal', 'position' => 'Secretary'],
        ['name' => 'Nandita Adhikari', 'position' => 'Vice President'],
        ['name' => 'Aanya Khadka', 'position' => 'Treasurer'],
        ['name' => 'Liza Sthapit', 'position' => 'Joint Secretary'],
        ['name' => 'Akrishta Dahal', 'position' => 'Sergeant-At-Arms'],
        ['name' => 'Simon Upreti', 'position' => 'Club Service Director'],
        ['name' => 'Subani KC', 'position' => 'Community Service Director'],
        ['name' => 'Yukie Maharjan', 'position' => 'Professional Development Director'],
        ['name' => 'Samriddhi Risal', 'position' => 'International Service Director + Public Image Chair'],
    ],
    'general_members' => [
        'Swapnil Upadhyay',
        'Shailesh Khadka',
        'Utsav Aryal',
        'Siril Budhathoki',
        'Shreya Khatiwada',
    ],
    'members_from_date' => [
        'date' => '2026-05-01',
        'members' => ['Smarika Maharjan', 'Siddhika Maharjan', 'Kimson Maharjan', 'Shalin Mohan Giri'],
    ],
    'minute_takers' => [
        'Suprim Dahal' => 'Secretary Rtr. Suprim Dahal',
        'Liza Sthapit' => 'Joint Secretary Rtr. Liza Sthapit',
    ],
    'signatures' => [
        'left' => ['name' => 'Rtr. Aakrity Rijal', 'title' => 'President', 'image' => 'assets/aakrity_sig.png'],
        'right' => ['name' => 'Rtr. Suprim Dahal', 'title' => 'Secretary', 'image' => 'assets/suprim_sig.png'],
    ],
    'stamp_image' => 'assets/rotary_stamp.png',
    'letterhead' => 'assets/letterhead.png',
    'footer_note' => 'Meeting Time: 11:00 am, Saturdays (bimonthly) E-mail: racpatansouth@gmail.com',

    'happy_sad_pool' => [
        'Rtr. Aanya shared that she adopted a rescue puppy over the weekend.',
        'Rtr. Suprim proudly announced completing a certification course in data analytics.',
        'Rtr. Liza expressed gratitude for the team\u2019s support during a recent personal challenge.',
        'Rtr. Aakrity celebrated her younger sibling\u2019s academic achievement.',
        'Rtr. Utsav shared news of his first marathon finish.',
        'Rtr. Priyanka received a promotion at work and treated the team.',
        'Rtr. Nirvisha shared her excitement about an upcoming trip to Pokhara.',
        'Rtr. Suprim mentioned his parents\u2019 wedding anniversary celebration.',
        'Rtr. Liza expressed joy over reconnecting with an old friend from school.',
        'Rtr. Aanya happily shared that her community garden project received funding.',
        'Rtr. Utsav completed a volunteer training program over the weekend.',
        'Rtr. Priyanka celebrated her mother\u2019s birthday with a family gathering.',
        'Rtr. Nirvisha shared news of her brother\u2019s academic success.',
        'Rtr. Aakrity mentioned recovering from a mild cold but feeling better now.',
        'Rtr. Surakshya shared that she completed a leadership workshop.',
        'Rtr. Nandita mentioned her family\u2019s annual reunion planning.',
        'Rtr. Utsav shared excitement about starting a new fitness routine.',
        'Rtr. Swapnil shared that he completed a month-long coding challenge.',
        'Rtr. Shailesh mentioned finishing a volunteer training program.',
        'Rtr. Shreya shared excitement about her art being featured in a local exhibition.',
        'Rtr. Siril mentioned completing a photography challenge.',
        'Rtr. Akrishta shared that he ran his first 5K over the weekend.',
        'Rtr. Simon shared news of his promotion at work.',
        'Rtr. Subani expressed gratitude for the team\u2019s support during a busy month.',
        'Rtr. Yukie celebrated a milestone in her professional certification.',
        'Rtr. Samriddhi shared excitement about an upcoming international exchange program.',
    ],

    'recurring_items' => [
        'generic' => [
            'The floor was opened for Any Other Business (AOB), during which members shared individual updates and announcements.',
            'Members were reminded to follow and share the club\'s social media pages across their personal networks to increase outreach.',
            'The Sergeant-At-Arms gently reminded members to maintain punctuality for future meetings.',
            'Members were encouraged to bring prospective members to the next meeting as part of the ongoing membership drive.',
            'The Secretary requested all members to submit pending event reports at the earliest.',
            'The President thanked all members for their continued enthusiasm and active participation in club activities.',
            'The Treasurer reminded members to collect their official club merchandise from the designated counter.',
            'Members were encouraged to share feedback and suggestions for improving meeting effectiveness.',
        ],
        'early' => [
            'The Treasurer provided an overview of the club budget for the current Rota Year, and members were briefed on the allocation across service pillars.',
            'The Board encouraged members to actively participate in upcoming events to build momentum for the year ahead.',
            'Members were reminded to complete their RI dues payment for the year. The Treasurer shared the payment details and deadline.',
            'The Secretary urged members to complete their registration on the official Rotary portal at the earliest convenience.',
        ],
        'mid' => [
            'The Treasurer provided an update on RI dues collection, noting that several members had yet to complete their payment.',
            'Members were reminded that the deadline for RI dues was approaching and were urged to settle their payments soon.',
            'The Secretary followed up on pending event reports from recent activities, requesting members to submit them promptly.',
            'The International Service Director shared updates on collaborative opportunities with international partner clubs.',
            'The Club Service Director encouraged members to renew their commitment to regular attendance and active involvement.',
            'The Professional Development Director highlighted upcoming training opportunities available through the district.',
        ],
        'late' => [
            'The Treasurer issued a final reminder for RI dues payment, noting that the deadline was fast approaching.',
            'Members were reminded to begin preparing their handover notes and reports for the end of the Rota Year.',
            'The President encouraged members to reflect on the year\'s achievements and share feedback for the incoming Board.',
            'Discussions were held on the transition process and the timeline for the upcoming election of the new Board.',
            'The Secretary reminded members that all club documentation and event reports must be finalized before the end of the Rota Year.',
            'The President expressed gratitude to the Board and members for their dedication throughout the year.',
        ],
    ],
];
